package com.github.simcityexpansion.buildpack;

import java.nio.file.Path;

import com.github.simcityexpansion.SimcityExpansion;
import net.minecraft.resources.ResourceLocation;
import net.neoforged.fml.loading.FMLPaths;

/**
 * 「建筑拓展包管理器 / BuildPack」功能的共享常量与工具方法。
 *
 * <p>BuildPack 是一个客户端 GUI，用于浏览本地导入目录中的建筑结构文件
 * （原版 {@code .nbt} 与 Litematica {@code .litematic} 投影）以及 zip 拓展包，
 * 编辑元数据后安装到 SimuKraft 的建筑目录（{@code <游戏目录>/simukraftbuilding/<分类>/}）。
 *
 * <p>与 SimuKraft 的集成为<b>纯文件系统约定</b>（写出 .sk + .nbt），不存在编译期依赖。
 */
public final class BuildPack {
  private BuildPack() {}

  /** 全部 BuildPack UI 元素使用的 CSS 类前缀，亦作为 LSS 选择器命名空间。 */
  public static final String STYLE_PREFIX = "buildpack";

  /** 唯一样式表：羊皮纸（原版）风格。 */
  public static final ResourceLocation STYLESHEET = lss("buildpack");

  /** 写入 .sk 文件首行的标记注释，用于识别由本模组生成/安装的建筑。 */
  public static final String GENERATED_MARKER = "generated by SimCity Expansion";

  /** 在本模组命名空间下创建资源路径。 */
  public static ResourceLocation id(String path) {
    return ResourceLocation.fromNamespaceAndPath(SimcityExpansion.MODID, path);
  }

  /** 在本模组命名空间下创建一个 LSS 样式表资源路径（{@code lss/<name>.lss}）。 */
  public static ResourceLocation lss(String name) {
    return id("lss/" + name + ".lss");
  }

  /** 拼接带前缀的 CSS 类名，例如 {@code cls("toolbar")} -> {@code "buildpack-toolbar"}。 */
  public static String cls(String suffix) {
    return STYLE_PREFIX + "-" + suffix;
  }

  /** 游戏根目录。 */
  public static Path gameDir() {
    return FMLPaths.GAMEDIR.get();
  }

  /** 散文件导入目录：用户把 .nbt / .litematic / zip 拓展包放进来。 */
  public static Path importDir() {
    return gameDir().resolve("simcity_expansion").resolve("import");
  }

  /** 已安装拓展包注册表文件（JSON）。 */
  public static Path registryFile() {
    return gameDir().resolve("simcity_expansion").resolve("installed_packs.json");
  }

  /** SimuKraft 的建筑根目录（其 BuildingCatalog 运行时扫描该目录）。 */
  public static Path simukraftDir() {
    return gameDir().resolve("simukraftbuilding");
  }
}
