package com.github.simcityexpansion.buildpack;

import java.nio.file.Path;

import com.github.simcityexpansion.SimcityExpansion;
import net.minecraft.resources.ResourceLocation;
import net.neoforged.fml.loading.FMLPaths;

/**
 * Shared constants and utility methods for the "build pack manager / BuildPack" feature.
 *
 * <p>BuildPack is a client GUI for browsing building structure files in the local import directory
 * (vanilla {@code .nbt} and Litematica {@code .litematic} schematics) as well as zip build packs,
 * editing metadata, and installing them into SimuKraft's building directory
 * ({@code <gameDir>/simukraftbuilding/<category>/}).
 *
 * <p>Integration with SimuKraft is a <b>pure file-system convention</b> (writing .sk + .nbt
 * files); there is no compile-time dependency.
 */
public final class BuildPack {
  private BuildPack() {}

  /** Marker comment written as the first line of .sk files to identify buildings generated or installed by this mod. */
  public static final String GENERATED_MARKER = "generated by SimCity Expansion";

  /** Creates a resource location under this mod's namespace. */
  public static ResourceLocation id(String path) {
    return ResourceLocation.fromNamespaceAndPath(SimcityExpansion.MODID, path);
  }

  /** Returns the game root directory. */
  public static Path gameDir() {
    return FMLPaths.GAMEDIR.get();
  }

  /** Loose-file import directory where users place .nbt, .litematic, and zip build packs. */
  public static Path importDir() {
    return gameDir().resolve("simcity_expansion").resolve("import");
  }

  /** Installed build pack registry file (JSON). */
  public static Path registryFile() {
    return gameDir().resolve("simcity_expansion").resolve("installed_packs.json");
  }

  /** SimuKraft's building root directory, scanned at runtime by its BuildingCatalog. */
  public static Path simukraftDir() {
    return gameDir().resolve("simukraftbuilding");
  }
}
