package com.github.simcityexpansion.buildpack;

import java.io.IOException;
import java.nio.file.AtomicMoveNotSupportedException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.HexFormat;

import com.github.simcityexpansion.SimcityExpansion;
import net.minecraft.resources.ResourceLocation;
import net.neoforged.fml.loading.FMLPaths;

/**
 * Shared constants and utility methods for the "build pack manager / BuildPack" feature.
 *
 * <p>BuildPack is a client GUI for browsing building structure files in the local import directory
 * (vanilla {@code .nbt} and Litematica {@code .litematic} schematics) as well as zip build packs,
 * editing metadata, and installing them into SimuKraft's building directory
 * ({@code <gameDir>/simukraftbuilding/<category>/}).
 *
 * <p>Integration with SimuKraft is a <b>pure file-system convention</b> (writing .sk + .nbt
 * files); there is no compile-time dependency.
 */
public final class BuildPack {
  private BuildPack() {}

  /** Marker comment written as the first line of .sk files to identify buildings generated or installed by this mod. */
  public static final String GENERATED_MARKER = "generated by SimCity Expansion";

  /** Maximum uncompressed size of a single file read out of a zip build pack (guards against zip bombs). */
  public static final long MAX_PACK_ENTRY_BYTES = 256L * 1024 * 1024;

  /** Maximum heap an NBT structure may allocate while decompressing/parsing (guards against decompression bombs). */
  public static final long MAX_STRUCTURE_NBT_BYTES = 1024L * 1024 * 1024;

  /** Maximum size of a pack {@code pack.json} / {@code index.json} JSON file. */
  public static final long MAX_PACK_JSON_BYTES = 8L * 1024 * 1024;

  /** Creates a resource location under this mod's namespace. */
  public static ResourceLocation id(String path) {
    return ResourceLocation.fromNamespaceAndPath(SimcityExpansion.MODID, path);
  }

  /** Returns the game root directory. */
  public static Path gameDir() {
    return FMLPaths.GAMEDIR.get();
  }

  /** Loose-file import directory where users place .nbt, .litematic, and zip build packs. */
  public static Path importDir() {
    return gameDir().resolve("simcity_expansion").resolve("import");
  }

  /** Installed build pack registry file (JSON). */
  public static Path registryFile() {
    return gameDir().resolve("simcity_expansion").resolve("installed_packs.json");
  }

  /**
   * Cache root for <b>activated</b> packs: converted structures live here (per pack, per category)
   * and are served to SimuKraft virtually via mixins, so activation writes nothing into
   * {@link #simukraftDir()}.
   */
  public static Path cacheDir() {
    return gameDir().resolve("simcity_expansion").resolve("cache");
  }

  /** Persisted set of currently active pack ids (JSON), re-applied on startup. */
  public static Path activePacksFile() {
    return gameDir().resolve("simcity_expansion").resolve("active_packs.json");
  }

  /**
   * SimuKraft's building root directory. Since SimuKraft 2.0 this directory holds <b>zip building
   * packages</b> ({@code *.zip} with the internal layout {@code buildings/<category>/<file>});
   * loose category directories are no longer read by SimuKraft.
   */
  public static Path simukraftDir() {
    return gameDir().resolve("simukraftbuilding");
  }

  /**
   * Backup directory that legacy loose building files ({@code simukraftbuilding/<category>/}, the
   * pre-2.0 SimuKraft layout) are moved into after being migrated into a managed zip. SimuKraft only
   * scans regular files in its root, so a subdirectory is invisible to it.
   */
  public static Path legacyBackupDir() {
    return simukraftDir().resolve("legacy_backup");
  }

  /**
   * Writes bytes to {@code target} atomically: the data is written to a sibling temporary file and
   * then moved into place, so a crash or power loss mid-write leaves the previous file intact rather
   * than a truncated/corrupt one. Falls back to a plain replace when the filesystem cannot move
   * atomically.
   */
  public static void writeAtomically(Path target, byte[] bytes) throws IOException {
    Path parent = target.getParent();
    if (parent != null) {
      Files.createDirectories(parent);
    }
    Path tmp = target.resolveSibling(target.getFileName() + ".tmp");
    Files.write(tmp, bytes);
    try {
      Files.move(tmp, target, StandardCopyOption.ATOMIC_MOVE, StandardCopyOption.REPLACE_EXISTING);
    } catch (AtomicMoveNotSupportedException e) {
      Files.move(tmp, target, StandardCopyOption.REPLACE_EXISTING);
    }
  }

  /** Returns the lowercase hex SHA-256 of the given bytes. */
  public static String sha256Hex(byte[] bytes) {
    try {
      return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(bytes));
    } catch (NoSuchAlgorithmException e) {
      // SHA-256 is mandated for every Java platform; this branch is unreachable.
      throw new IllegalStateException(e);
    }
  }
}
